### ISSUE TITLE
Database access error when updating container version

### ISSUE THREAD

**Issue by ericbaum** [dojot/device-manager#51]
After updating the device-manager from the tag version 0.2.0-nightly20180321 to tag version 0.2.0-nightly20180326 the database model became inconsistent with the module returning the following error:

```
 [SQL: 'SELECT anon_1.templates_id AS anon_1_templates_id, anon_1.templates_label AS anon_1_templates_label, anon_1.templates_created AS anon_1_templates_created, anon_1.templates_updated AS anon_1_templates_updated, attrs_1.id AS attrs_1_id, attrs_1.label AS attrs_1_label, attrs_1.created AS attrs_1_created, attrs_1.updated AS attrs_1_updated, attrs_1.type AS attrs_1_type, attrs_1.value_type AS attrs_1_value_type, attrs_1.static_value AS attrs_1_static_value, attrs_1.template_id AS attrs_1_template_id, attrs_1.parent_id AS attrs_1_parent_id \nFROM (SELECT templates.id AS templates_id, templates.label AS templates_label, templates.created AS templates_created, templates.updated AS templates_updated \nFROM templates \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN attrs AS attrs_1 ON anon_1.templates_id = attrs_1.template_id'] [parameters: {'param_1': 20, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
10.46.0.11 - - [26/Mar/2018:16:15:26 +0000] "GET /template HTTP/1.1" 500 25 "http://10.50.11.32/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
[2018-03-26 16:15:47,457] ERROR in app: Exception on /template [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column attrs_1.parent_id does not exist
LINE 1: ...alue, attrs_1.template_id AS attrs_1_template_id, attrs_1.pa...
```
To avoid this kind of issue it is necessary implementing some sort of database versioning and migration functionalities for when there are model changes.

**Comment by rascaraficci** [comment]
Closed due to inactivity.
